import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import { Loader2, Plus, MapPin, CreditCard } from "lucide-react";
import { useCart } from "@/hooks/useCart";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

interface Address {
  id: string;
  address_title: string;
  full_name: string;
  phone: string;
  street_address: string;
  building_unit: string | null;
  city: string;
  state_province: string;
  country: string;
  postal_code: string | null;
  is_default: boolean;
}

const Checkout = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const { cartItems, subtotal, shippingCost, total, clearCart } = useCart();
  const [addresses, setAddresses] = useState<Address[]>([]);
  const [selectedAddress, setSelectedAddress] = useState<string>("");
  const [paymentMethod, setPaymentMethod] = useState<string>("cod");
  const [loading, setLoading] = useState(true);
  const [placing, setPlacing] = useState(false);

  useEffect(() => {
    if (!user) {
      navigate("/auth");
      return;
    }

    if (cartItems.length === 0) {
      navigate("/cart");
      return;
    }

    fetchAddresses();
  }, [user, cartItems]);

  const fetchAddresses = async () => {
    try {
      const { data, error } = await supabase
        .from("addresses")
        .select("*")
        .eq("user_id", user!.id)
        .order("is_default", { ascending: false })
        .order("created_at", { ascending: false });

      if (error) throw error;

      setAddresses(data || []);
      
      // Auto-select default address
      const defaultAddr = data?.find(addr => addr.is_default);
      if (defaultAddr) {
        setSelectedAddress(defaultAddr.id);
      }
    } catch (error) {
      console.error("Error fetching addresses:", error);
      toast.error("Failed to load addresses");
    } finally {
      setLoading(false);
    }
  };

  const handlePlaceOrder = async () => {
    if (!selectedAddress) {
      toast.error("Please select a shipping address");
      return;
    }

    if (!paymentMethod) {
      toast.error("Please select a payment method");
      return;
    }

    setPlacing(true);

    try {
      const address = addresses.find(a => a.id === selectedAddress);
      if (!address) throw new Error("Address not found");

      // Create order
      const { data: order, error: orderError } = await supabase
        .from("orders")
        .insert([{
          customer_id: user!.id,
          order_number: '', // Will be auto-generated by trigger
          subtotal,
          shipping_cost: shippingCost,
          total,
          payment_method: paymentMethod,
          payment_status: paymentMethod === "cod" ? "pending" : "pending",
          status: "pending",
          shipping_address: {
            full_name: address.full_name,
            phone: address.phone,
            street_address: address.street_address,
            building_unit: address.building_unit,
            city: address.city,
            state_province: address.state_province,
            country: address.country,
            postal_code: address.postal_code,
          } as any,
        }])
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items
      const orderItems = cartItems.map(item => ({
        order_id: order.id,
        product_id: item.product_id,
        product_name: item.product?.name || "",
        quantity: item.quantity,
        unit_price: item.product?.price || 0,
        subtotal: (item.product?.price || 0) * item.quantity,
      }));

      const { error: itemsError } = await supabase
        .from("order_items")
        .insert(orderItems);

      if (itemsError) throw itemsError;

      // Clear cart
      await clearCart();

      toast.success("Order placed successfully!");
      navigate(`/orders/${order.id}`);
    } catch (error) {
      console.error("Error placing order:", error);
      toast.error("Failed to place order. Please try again.");
    } finally {
      setPlacing(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      <main className="flex-1 bg-muted/20">
        <div className="container mx-auto px-4 py-8">
          <h1 className="font-heading font-bold text-3xl mb-8">Checkout</h1>

          <div className="grid lg:grid-cols-3 gap-8">
            {/* Checkout Form */}
            <div className="lg:col-span-2 space-y-6">
              {/* Shipping Address */}
              <Card className="p-6">
                <div className="flex items-center justify-between mb-4">
                  <h2 className="font-heading font-semibold text-xl flex items-center gap-2">
                    <MapPin className="h-5 w-5 text-primary" />
                    Shipping Address
                  </h2>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => navigate("/profile/address-book")}
                  >
                    <Plus className="h-4 w-4 mr-2" />
                    Add New
                  </Button>
                </div>

                {addresses.length === 0 ? (
                  <div className="text-center py-8 text-muted-foreground">
                    <p className="mb-4">No saved addresses found</p>
                    <Button onClick={() => navigate("/profile/address-book")}>
                      Add Address
                    </Button>
                  </div>
                ) : (
                  <RadioGroup value={selectedAddress} onValueChange={setSelectedAddress}>
                    <div className="space-y-3">
                      {addresses.map((address) => (
                        <div
                          key={address.id}
                          className="flex items-start gap-3 border border-border rounded-lg p-4 cursor-pointer hover:bg-muted/50"
                          onClick={() => setSelectedAddress(address.id)}
                        >
                          <RadioGroupItem value={address.id} id={address.id} />
                          <Label htmlFor={address.id} className="flex-1 cursor-pointer">
                            <div className="font-semibold mb-1">
                              {address.address_title}
                              {address.is_default && (
                                <span className="ml-2 text-xs bg-primary text-primary-foreground px-2 py-0.5 rounded">
                                  Default
                                </span>
                              )}
                            </div>
                            <div className="text-sm text-muted-foreground">
                              <p>{address.full_name} • {address.phone}</p>
                              <p>
                                {address.street_address}
                                {address.building_unit && `, ${address.building_unit}`}
                              </p>
                              <p>
                                {address.city}, {address.state_province} {address.postal_code}
                              </p>
                              <p>{address.country}</p>
                            </div>
                          </Label>
                        </div>
                      ))}
                    </div>
                  </RadioGroup>
                )}
              </Card>

              {/* Payment Method */}
              <Card className="p-6">
                <h2 className="font-heading font-semibold text-xl mb-4 flex items-center gap-2">
                  <CreditCard className="h-5 w-5 text-primary" />
                  Payment Method
                </h2>

                <RadioGroup value={paymentMethod} onValueChange={setPaymentMethod}>
                  <div className="space-y-3">
                    <div
                      className="flex items-center gap-3 border border-border rounded-lg p-4 cursor-pointer hover:bg-muted/50"
                      onClick={() => setPaymentMethod("cod")}
                    >
                      <RadioGroupItem value="cod" id="cod" />
                      <Label htmlFor="cod" className="flex-1 cursor-pointer">
                        <div className="font-semibold">Cash on Delivery</div>
                        <div className="text-sm text-muted-foreground">Pay when you receive</div>
                      </Label>
                    </div>

                    <div
                      className="flex items-center gap-3 border border-border rounded-lg p-4 cursor-pointer hover:bg-muted/50"
                      onClick={() => setPaymentMethod("syriatel")}
                    >
                      <RadioGroupItem value="syriatel" id="syriatel" />
                      <Label htmlFor="syriatel" className="flex-1 cursor-pointer">
                        <div className="font-semibold">Syriatel Cash</div>
                        <div className="text-sm text-muted-foreground">Pay with Syriatel mobile wallet</div>
                      </Label>
                    </div>

                    <div
                      className="flex items-center gap-3 border border-border rounded-lg p-4 cursor-pointer hover:bg-muted/50"
                      onClick={() => setPaymentMethod("mtn")}
                    >
                      <RadioGroupItem value="mtn" id="mtn" />
                      <Label htmlFor="mtn" className="flex-1 cursor-pointer">
                        <div className="font-semibold">MTN Cash</div>
                        <div className="text-sm text-muted-foreground">Pay with MTN mobile wallet</div>
                      </Label>
                    </div>
                  </div>
                </RadioGroup>
              </Card>
            </div>

            {/* Order Summary */}
            <div className="lg:col-span-1">
              <Card className="p-6 sticky top-24">
                <h2 className="font-heading font-semibold text-xl mb-4">Order Summary</h2>
                
                <div className="space-y-3 mb-4 max-h-64 overflow-y-auto">
                  {cartItems.map((item) => (
                    <div key={item.id} className="flex gap-3 text-sm">
                      <div className="w-12 h-12 bg-muted rounded flex items-center justify-center text-2xl">
                        📦
                      </div>
                      <div className="flex-1">
                        <p className="font-medium line-clamp-1">{item.product?.name}</p>
                        <p className="text-muted-foreground">Qty: {item.quantity}</p>
                      </div>
                      <div className="font-medium">
                        ${((item.product?.price || 0) * item.quantity).toFixed(2)}
                      </div>
                    </div>
                  ))}
                </div>

                <div className="space-y-3 border-t border-border pt-4 mb-6">
                  <div className="flex justify-between text-sm">
                    <span className="text-muted-foreground">Subtotal</span>
                    <span className="font-medium">${subtotal.toFixed(2)}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-muted-foreground">Shipping</span>
                    <span className="font-medium">
                      {shippingCost === 0 ? "FREE" : `$${shippingCost.toFixed(2)}`}
                    </span>
                  </div>
                  <div className="border-t border-border pt-3 flex justify-between">
                    <span className="font-heading font-semibold">Total</span>
                    <span className="font-heading font-bold text-xl text-primary">
                      ${total.toFixed(2)}
                    </span>
                  </div>
                </div>

                <Button
                  className="w-full"
                  size="lg"
                  onClick={handlePlaceOrder}
                  disabled={placing || !selectedAddress || !paymentMethod}
                >
                  {placing ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Placing Order...
                    </>
                  ) : (
                    "Place Order"
                  )}
                </Button>
              </Card>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Checkout;
